### ISSUE TITLE
Few errors

### ISSUE THREAD

**Issue by Lolicon-Mindustry** [Opofde/More-Ore-v1.0#4]
![Screenshot_20200306-085528](https://user-images.githubusercontent.com/59752736/76059762-6309d080-5f88-11ea-9221-8ce71aaf88f4.jpg)
![Screenshot_20200306-085532](https://user-images.githubusercontent.com/59752736/76059767-643afd80-5f88-11ea-8b05-fb2f7f6e473e.jpg)
![Screenshot_20200306-085521](https://user-images.githubusercontent.com/59752736/76059769-64d39400-5f88-11ea-863b-10ca4e4497c8.jpg)
![Screenshot_20200306-085537](https://user-images.githubusercontent.com/59752736/76059772-6604c100-5f88-11ea-9040-3d36199ceba5.jpg)

**Comment by Lolicon-Mindustry** [comment]
Ver: 104.5

**Comment by Opofde** [comment]
Thanks for your comment!
This issue was already discovered, but i had no time to fix it.

Opofde
